/* this register map header originates from pzPowerI2C GIT repository */

#define PZP_I2C_REG_VOLTAGE_INPUT_NOW             0
#define PZP_I2C_REG_VOLTAGE_INPUT_AVG             1
#define PZP_I2C_REG_TEMPERATURE_BOARD_NOW         2
#define PZP_I2C_REG_TEMPERATURE_BOARD_AVG         3
#define PZP_I2C_REG_SWITCH_MAGNET_NOW             4
#define PZP_I2C_REG_SWITCH_MAGNET_LATCH           5
#define PZP_I2C_REG_SEQUENCE_NUMBER               6
#define PZP_I2C_REG_TIME_INTERVAL_MILLISECONDS    7
#define PZP_I2C_REG_TIME_UPTIME_MINUTES           8
#define PZP_I2C_REG_TIME_WATCHDOG_READ_SECONDS    9
#define PZP_I2C_REG_TIME_WATCHDOG_WRITE_SECONDS   10
#define PZP_I2C_REG_DEFAULT_PARAMS_WRITTEN        11
#define PZP_I2C_REG_COMMAND_OFF                   12
#define PZP_I2C_REG_POWER_OFF_FLAGS               14



#define PZP_I2C_REG_CONFIG_SERIAL_PREFIX                32
#define PZP_I2C_REG_CONFIG_SERIAL_NUMBER                33
#define PZP_I2C_REG_CONFIG_HARDWARE_MODEL               34
#define PZP_I2C_REG_CONFIG_HARDWARE_VERSION             35
#define PZP_I2C_REG_CONFIG_SOFTWARE_MODEL               36
#define PZP_I2C_REG_CONFIG_SOFTWARE_VERSION             37
#define PZP_I2C_REG_CONFIG_SOFTWARE_YEAR                38
#define PZP_I2C_REG_CONFIG_SOFTWARE_MONTH               39
#define PZP_I2C_REG_CONFIG_SOFTWARE_DAY                 40
#define PZP_I2C_REG_CONFIG_PARAM_WRITE                  41
#define PZP_I2C_REG_CONFIG_TICKS_ADC                    42
#define PZP_I2C_REG_CONFIG_STARTUP_POWER_ON_DELAY       43
#define PZP_I2C_REG_CONFIG_COMMAND_OFF_HOLD_TIME        44
#define PZP_I2C_REG_CONFIG_READ_WATCHDOG_OFF_THRESHOLD  45
#define PZP_I2C_REG_CONFIG_READ_WATCHDOG_OFF_HOLD_TIME  46
#define PZP_I2C_REG_CONFIG_WRITE_WATCHDOG_OFF_THRESHOLD 47
#define PZP_I2C_REG_CONFIG_WRITE_WATCHDOG_OFF_HOLD_TIME 48
#define PZP_I2C_REG_CONFIG_LVD_DISCONNECT_VOLTAGE       49
#define PZP_I2C_REG_CONFIG_LVD_DISCONNECT_DELAY         50
#define PZP_I2C_REG_CONFIG_LVD_RECONNECT_VOLTAGE        51
#define PZP_I2C_REG_CONFIG_HVD_DISCONNECT_VOLTAGE       52
#define PZP_I2C_REG_CONFIG_HVD_DISCONNECT_DELAY         53
#define PZP_I2C_REG_CONFIG_HVD_RECONNECT_VOLTAGE        54
